# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 05:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_type', models.CharField(choices=[('HOME', 'home'), ('WORK', 'work')], default='HOME', max_length=4)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=19)),
                ('phone_type', models.CharField(choices=[('HOME', 'home'), ('WORK', 'work')], default='HOME', max_length=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contactPictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
