# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_type', models.CharField(choices=[('HOME', 'home'), ('WORK', 'work')], default='HOME', max_length=4)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=19)),
                ('phone_type', models.CharField(choices=[('HOME', 'home'), ('WORK', 'work')], default='HOME', max_length=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contactPictures')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
